baseURL = "https://obsidian.codeplayer.org/"
timeZone = "Asia/Shanghai"
languageCode = "zh-cn"
googleAnalytics = "G-PCXDEM5E1Q"
relativeURLs = false
disablePathToLower = true
ignoreFiles = [
    "/content/+ Encounters/*",
    "/content/Atlas/*",
    "/content/Calendar/*",
    "/content/Cards/中医/*",
    "/content/Extras/Templater/*",
    "/content/Space/*",
    "/content/HOMEPAGE",
]
summaryLength = 20
paginate = 10
enableGitInfo = true

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 1
    [markup.highlight]
        noClasses = false
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]
        date = [":default", "date modified"]
        lastmod = ["lastmod", ":git", "date", "publishDate", "date modified"]
        publishDate = ["publishDate", "date", "date modified"]
    [markup.goldmark.renderer]
        unsafe = true
